### ISSUE TITLE
Paste Compiles with Problems

### ISSUE THREAD

**Issue by cweems** [twilio-labs/paste#2097]
Hi there and thanks for looking at my bug report!

**Describe the bug**
When I run `yarn start` I get the following error displayed in the browser:

```
Compiled with problems:X

ERROR in ./node_modules/@twilio-paste/color-contrast-utils/dist/index.es.js 1907:13-15

Should not import the named export 'props' (imported as 'Ie') from default-exporting module (only default export is available soon)


ERROR in ./node_modules/@twilio-paste/color-contrast-utils/dist/index.es.js 1912:13-15

Should not import the named export 'props' (imported as 'Ie') from default-exporting module (only default export is available soon)


ERROR in ./node_modules/@twilio-paste/style-props/dist/index.es.js 404:22-24

Should not import the named export 'props' (imported as 'ae') from default-exporting module (only default export is available soon)

```

**To Reproduce**
Use node 16.13.1
Use yarn 1.22.17

Run:

```shell
yarn create react-app --template @twilio-paste my-paste-app
cd my-paste-app
yarn start
```
**Expected behavior**
Expected started app to compile successfully.

**Screenshots**
<img width="1596" alt="Screen Shot 2021-12-14 at 5 23 30 PM" src="https://user-images.githubusercontent.com/1418949/146105517-c1376e00-9454-4f44-b163-11a9f90377a9.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.0.1
 - Browser: Chrome 96

**Additional context**
First time Paste installer! Create React App runs successfully on its own.

**Comment by SiTaggart** [comment]
Hi there,

Yup, this is a known issue, not helped with webpack v5 being made the default for create react app and next.js. 

I'll see if we can get this bumped up sooner rather than later.

In the meantime, if there's an option to use Webpack v4 this error should go away.

**Comment by cweems** [comment]
@SiTaggart thank you. I'm a bit new to create-react-app so apologies if this is obvious: how would I go about specifying Webpack V4? It seems like I need to either eject the app or use craco? Or maybe there's a supported version of create-react-app I should roll back to?

**Comment by cweems** [comment]
Thanks, that worked for me! Would you appreciate a PR to the docs quickstart page to let others know about this issue? I would be happy to make one.

**Comment by SiTaggart** [comment]
Hi @cweems This should be fixed now if you update Paste core.

Thanks!

**Comment by younessssssss** [comment]
hi @SiTaggart , i have the last version "@twilio-paste/core": "^10.19.0",but i still have the same compile error 
"ERROR in ./node_modules/@twilio-paste/style-props/dist/index.es.js 404:22-24"

**Comment by SiTaggart** [comment]
Hi @younessssssss 

We'll be doing a release later today to get the remaining warning cleared up.

**Comment by SiTaggart** [comment]
Hi @younessssssss, Paste Core v10.20 should be out now. Let us know if you run into anymore errors, but I'm pretty sure we've got them all now.

Thanks!

**Comment by SiTaggart** [comment]
Hi @younessssssss 

Do you mind creating a minimal reproduction in CodeSandbox for us to help isolate the problem?

We don't bundle or redistribute react-router or react-router-dom with Paste. We don't even have a dependency on it, so it's odd to see react router errors.

**Comment by younessssssss** [comment]
@SiTaggart sorry i did not explain well ,this error come from `paste-cra-template`, the twilio-past  template created with create-react-app ,every thing is fine with past core ,i will try to update the version of ` react-router-dom` and see.
