### ISSUE TITLE
Warnings from ResetButton

### ISSUE THREAD

**Issue by ghostling** [twilio-labs/paste#712]
Hi, I'm seeing these three warnings in console output when using `<Button size="reset">`: 
```
Warning: Failed prop type: [Box]: invalid prop supplied "fontSize=inherit", expected a token value. See https://paste.twilio.design/tokens for available options.
    in Box (created by ResetButton)
    in ResetButton (created by Button)
    in Button (created by ForwardRef(TooltipReference))
    in ForwardRef(TooltipReference) (created by Tooltip)
    in Tooltip (created by OrderItemsTable)
    ...<trimmed>...

Warning: Failed prop type: [Box]: invalid prop supplied "fontWeight=inherit", expected a token value. See https://paste.twilio.design/tokens for available options.
    ...<trimmed>...

errorCollection.js:61 Warning: Failed prop type: [Box]: invalid prop supplied "color=inherit", expected a token value. See https://paste.twilio.design/tokens for available options.
    ...<trimmed>...
```

Probably comes from here? https://github.com/twilio-labs/paste/blob/main/packages/paste-core/components/button/src/ResetButton.tsx#L9-L13

**Comment by SiTaggart** [comment]
Hi @ghostling, I noticed this and am having to fix it in another PR soon.

Thanks for dropping us a note 🙇

**Comment by SiTaggart** [comment]
@ghostling this should be fixed now. Please update your dependencies and grab the latest code. 

Let us know either way, so we can close this out.

**Comment by ghostling** [comment]
Made sure all the paste dependencies we have are up to date, but still seeing two warnings with `fontWeight=inherit` and `color=inherit`. What did I miss? 
```
    "@twilio-paste/animation-library": "^0.2.1",
    "@twilio-paste/core": "^2.16.46",
    "@twilio-paste/design-tokens": "^6.3.0",
    "@twilio-paste/dropdown-library": "^0.1.2",
    "@twilio-paste/icons": "^3.2.1",
    "@twilio-paste/reakit-library": "^0.7.0",
    "@twilio-paste/style-props": "^1.6.1",
    "@twilio-paste/styling-library": "^0.1.2",
    "@twilio-paste/theme": "^3.2.19",
    "@twilio-paste/types": "^3.0.22",
```

Also, side note, it's not immediately clear which one to update first... I started with core, design-tokens, types, etc, until all of them are updated, but I noticed this is my "upgrade strategy" when I do need to upgrade to pick up a fix.

**Comment by SiTaggart** [comment]
@ghostling Don't mind me, I only updated one of props that need inherit and it was neither fontWeight or color 🤦

**Comment by SiTaggart** [comment]
@ghostling I think I got it now, update the deps and see what happens

**Comment by ghostling** [comment]
All good now! Thank you!
